// react-todo-app/src/App.js
import { useCallback, useState } from 'react';

let id = 0;

const DEFAULT_TASK = { id: 0, title: '', description: '', isDone: false };

const App = () => {
  const [tasks, setTasks] = useState([]);
  const [newTask, setNewTask] = useState(DEFAULT_TASK);

  const onSubmit = useCallback((e) => {
    const task = {
      ...newTask,
      id: ++id,
    };

    setTasks([task, ...tasks]);

    setNewTask(DEFAULT_TASK)

    e.preventDefault();
  }, [tasks, newTask]);

  const onDeleteTask = useCallback((id) => {
    const newTasks = tasks.filter(task => task.id !== id);
    setTasks(newTasks);
  }, [tasks]);

  const onUpdateTask = useCallback((task) => {
    const newTasks = tasks.map(_task => _task.id === task.id ? { ...task } : _task)
    setTasks(newTasks);
  }, [tasks]);

  return (
    <div>

      <div className='create-task'>
        <form onSubmit={onSubmit}>
          <input className='input' type="text" value={newTask.title} onInput={(e) => setNewTask({
              ...newTask,
              title: e.target.value,
            })}
          />
          <input className='input' type="text" value={newTask.description} onInput={(e) => setNewTask({
              ...newTask,
              description: e.target.value,
            })}
          />

          <button className='button' type="submit">Добавить</button>
        </form>
      </div>

      <div className='tasks-list'>
        {
          tasks.length > 0 && (<ul className='list'>
            {tasks.map(task => (
              <li className='list-item' key={task.id}>
                <div className='item-col item-col--title'>{task.title}</div>
                <div className='item-col item-col--description'>{task.description}</div>
                <input className='item-col item-col--is-done' type="checkbox" name="isDone" value={task.isDone} onChange={() => onUpdateTask({ ...task, isDone: !task.isDone })} />
                <button className='item-col item-col--delete' onClick={() => onDeleteTask(task.id)}>Удалить</button>
              </li>
            ))}
        </ul>)
        }

      </div>

    </div>
  );
}

export default App;

// solid-todo-app/src/App.jsx
import { Show, createSignal } from "solid-js";

let id = 0;
const DEFAULT_TASK = {
  title: '',
  description: '',
  isDone: false,
}

const App = () => {
  const [tasks, setTasks] = createSignal([]);
  const [newTask, setNewTask] = createSignal({ ...DEFAULT_TASK });


  const onSubmit = (e) => {
    e.preventDefault();
    setTasks([ { ...newTask(), isDone: false, createdAt: new Date(), id: ++id }, ...tasks() ]);
    setNewTask({ ...DEFAULT_TASK });
  }

  const onAddNewTitle = (e) => {
    setNewTask({ ...newTask(), title: e.target.value });
  }

  const onAddNewDescription = (e) => {
    setNewTask({ ...newTask(), description: e.target.value });
  }

  const onDeleteTask = (id) => {
    const newTasks = tasks().filter(task => task.id !== id);
    setTasks(newTasks);
  }

  const onUpdateTask = (updatedTask) => {
    const newTasks = tasks().map(task => task.id === updatedTask.id ? { ...updatedTask } : task);
    setTasks(newTasks);
  }


  return (
    <div>
      <div class="create-task">
        <form onSubmit={onSubmit}>
          <input class="input" type="text" value={newTask().title} onInput={onAddNewTitle} />
          <input class="input" type="text" value={newTask().description} onInput={onAddNewDescription} />
          <button class="button" type="submit">Добавить</button>
        </form>
      </div>


      <div class="tasks-list">
        <Show when={tasks().length > 0}>
          <ul class="list">
            <For each={tasks()}>{(task, i) =>
              <li class="list-item">
                <div class="item-col item-col--title">{task.title}</div>
                <div class="item-col item-col--description">{task.description}</div>
                <input class="item-col item-col--is-done" type="checkbox" value={task.isDone} onChange={() => onUpdateTask({ ...task, isDone: !task.isDone })} />
                <button class="item-col item-col--delete" onClick={() => onDeleteTask(task.id)}>Удалить</button>
              </li>
            }</For>
          </ul>
        </Show>
      </div>
    </div>
  )

}

export default App;
